# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# module Hello
#   describe SessionsController do

#     # This should return the minimal set of attributes required to create a valid
#     # Session. As you add validations to Session, be sure to
#     # adjust the attributes here as well.
#     let(:valid_attributes) { { "ua" => "MyString" } }

#     # This should return the minimal set of values that should be in the session
#     # in order to pass any filters (e.g. authentication) defined in
#     # SessionsController. Be sure to keep this updated too.
#     let(:valid_session) { {} }

#     describe "GET index" do
#       it "assigns all sessions as @sessions" do
#         session = Session.create! valid_attributes
#         get :index, {}, valid_session
#         expect(assigns(:sessions)).to eq([session])
#       end
#     end

#     describe "GET show" do
#       it "assigns the requested session as @session" do
#         session = Session.create! valid_attributes
#         get :show, {:id => session.to_param}, valid_session
#         expect(assigns(:session)).to eq(session)
#       end
#     end

#     describe "GET new" do
#       it "assigns a new session as @session" do
#         get :new, {}, valid_session
#         expect(assigns(:session)).to be_a_new(Session)
#       end
#     end

#     describe "GET edit" do
#       it "assigns the requested session as @session" do
#         session = Session.create! valid_attributes
#         get :edit, {:id => session.to_param}, valid_session
#         expect(assigns(:session)).to eq(session)
#       end
#     end

#     describe "POST create" do
#       describe "with valid params" do
#         it "creates a new Session" do
#           expect {
#             post :create, {:session => valid_attributes}, valid_session
#           }.to change(Session, :count).by(1)
#         end

#         it "assigns a newly created session as @session" do
#           post :create, {:session => valid_attributes}, valid_session
#           expect(assigns(:session)).to be_a(Session)
#           expect(assigns(:session)).to be_persisted
#         end

#         it "redirects to the created session" do
#           post :create, {:session => valid_attributes}, valid_session
#           expect(response).to redirect_to(Session.last)
#         end
#       end

#       describe "with invalid params" do
#         it "assigns a newly created but unsaved session as @session" do
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Session).to receive(:save).and_return(false)
#           post :create, {:session => { "ua" => "invalid value" }}, valid_session
#           expect(assigns(:session)).to be_a_new(Session)
#         end

#         it "re-renders the 'new' template" do
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Session).to receive(:save).and_return(false)
#           post :create, {:session => { "ua" => "invalid value" }}, valid_session
#           expect(response).to render_template("new")
#         end
#       end
#     end

#     describe "PUT update" do
#       describe "with valid params" do
#         it "updates the requested session" do
#           session = Session.create! valid_attributes
#           # Assuming there are no other sessions in the database, this
#           # specifies that the Session created on the previous line
#           # receives the :update_attributes message with whatever params are
#           # submitted in the request.
#           expect_any_instance_of(Session).to receive(:update).with({ "ua" => "MyString" })
#           put :update, {:id => session.to_param, :session => { "ua" => "MyString" }}, valid_session
#         end

#         it "assigns the requested session as @session" do
#           session = Session.create! valid_attributes
#           put :update, {:id => session.to_param, :session => valid_attributes}, valid_session
#           expect(assigns(:session)).to eq(session)
#         end

#         it "redirects to the session" do
#           session = Session.create! valid_attributes
#           put :update, {:id => session.to_param, :session => valid_attributes}, valid_session
#           expect(response).to redirect_to(session)
#         end
#       end

#       describe "with invalid params" do
#         it "assigns the session as @session" do
#           session = Session.create! valid_attributes
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Session).to receive(:save).and_return(false)
#           put :update, {:id => session.to_param, :session => { "ua" => "invalid value" }}, valid_session
#           expect(assigns(:session)).to eq(session)
#         end

#         it "re-renders the 'edit' template" do
#           session = Session.create! valid_attributes
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Session).to receive(:save).and_return(false)
#           put :update, {:id => session.to_param, :session => { "ua" => "invalid value" }}, valid_session
#           expect(response).to render_template("edit")
#         end
#       end
#     end

#     describe "DELETE destroy" do
#       it "destroys the requested session" do
#         session = Session.create! valid_attributes
#         expect {
#           delete :destroy, {:id => session.to_param}, valid_session
#         }.to change(Session, :count).by(-1)
#       end

#       it "redirects to the sessions list" do
#         session = Session.create! valid_attributes
#         delete :destroy, {:id => session.to_param}, valid_session
#         expect(response).to redirect_to(sessions_url)
#       end
#     end

#   end
# end
