# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# module Hello
#   describe IdentitiesController do

#     # This should return the minimal set of attributes required to create a valid
#     # Identity. As you add validations to Identity, be sure to
#     # adjust the attributes here as well.
#     let(:valid_attributes) { { "email" => "MyString" } }

#     # This should return the minimal set of values that should be in the session
#     # in order to pass any filters (e.g. authentication) defined in
#     # IdentitiesController. Be sure to keep this updated too.
#     let(:valid_session) { {} }

#     describe "GET index" do
#       it "assigns all identities as @identities" do
#         identity = Identity.create! valid_attributes
#         get :index, {}, valid_session
#         expect(assigns(:identities)).to eq([identity])
#       end
#     end

#     describe "GET show" do
#       it "assigns the requested identity as @identity" do
#         identity = Identity.create! valid_attributes
#         get :show, {:id => identity.to_param}, valid_session
#         expect(assigns(:identity)).to eq(identity)
#       end
#     end

#     describe "GET new" do
#       it "assigns a new identity as @identity" do
#         get :new, {}, valid_session
#         expect(assigns(:identity)).to be_a_new(Identity)
#       end
#     end

#     describe "GET edit" do
#       it "assigns the requested identity as @identity" do
#         identity = Identity.create! valid_attributes
#         get :edit, {:id => identity.to_param}, valid_session
#         expect(assigns(:identity)).to eq(identity)
#       end
#     end

#     describe "POST create" do
#       describe "with valid params" do
#         it "creates a new Identity" do
#           expect {
#             post :create, {:identity => valid_attributes}, valid_session
#           }.to change(Identity, :count).by(1)
#         end

#         it "assigns a newly created identity as @identity" do
#           post :create, {:identity => valid_attributes}, valid_session
#           expect(assigns(:identity)).to be_a(Identity)
#           expect(assigns(:identity)).to be_persisted
#         end

#         it "redirects to the created identity" do
#           post :create, {:identity => valid_attributes}, valid_session
#           expect(response).to redirect_to(Identity.last)
#         end
#       end

#       describe "with invalid params" do
#         it "assigns a newly created but unsaved identity as @identity" do
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Identity).to receive(:save).and_return(false)
#           post :create, {:identity => { "email" => "invalid value" }}, valid_session
#           expect(assigns(:identity)).to be_a_new(Identity)
#         end

#         it "re-renders the 'new' template" do
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Identity).to receive(:save).and_return(false)
#           post :create, {:identity => { "email" => "invalid value" }}, valid_session
#           expect(response).to render_template("new")
#         end
#       end
#     end

#     describe "PUT update" do
#       describe "with valid params" do
#         it "updates the requested identity" do
#           identity = Identity.create! valid_attributes
#           # Assuming there are no other identities in the database, this
#           # specifies that the Identity created on the previous line
#           # receives the :update_attributes message with whatever params are
#           # submitted in the request.
#           expect_any_instance_of(Identity).to receive(:update).with({ "email" => "MyString" })
#           put :update, {:id => identity.to_param, :identity => { "email" => "MyString" }}, valid_session
#         end

#         it "assigns the requested identity as @identity" do
#           identity = Identity.create! valid_attributes
#           put :update, {:id => identity.to_param, :identity => valid_attributes}, valid_session
#           expect(assigns(:identity)).to eq(identity)
#         end

#         it "redirects to the identity" do
#           identity = Identity.create! valid_attributes
#           put :update, {:id => identity.to_param, :identity => valid_attributes}, valid_session
#           expect(response).to redirect_to(identity)
#         end
#       end

#       describe "with invalid params" do
#         it "assigns the identity as @identity" do
#           identity = Identity.create! valid_attributes
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Identity).to receive(:save).and_return(false)
#           put :update, {:id => identity.to_param, :identity => { "email" => "invalid value" }}, valid_session
#           expect(assigns(:identity)).to eq(identity)
#         end

#         it "re-renders the 'edit' template" do
#           identity = Identity.create! valid_attributes
#           # Trigger the behavior that occurs when invalid params are submitted
#           allow_any_instance_of(Identity).to receive(:save).and_return(false)
#           put :update, {:id => identity.to_param, :identity => { "email" => "invalid value" }}, valid_session
#           expect(response).to render_template("edit")
#         end
#       end
#     end

#     describe "DELETE destroy" do
#       it "destroys the requested identity" do
#         identity = Identity.create! valid_attributes
#         expect {
#           delete :destroy, {:id => identity.to_param}, valid_session
#         }.to change(Identity, :count).by(-1)
#       end

#       it "redirects to the identities list" do
#         identity = Identity.create! valid_attributes
#         delete :destroy, {:id => identity.to_param}, valid_session
#         expect(response).to redirect_to(identities_url)
#       end
#     end

#   end
# end
